package problem044;

import java.util.ArrayList;

/**
 * Created by kiran on 1/19/16.
 *
 * Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

 It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

 Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
 */
public class Problem044 {


    public static void main(String[] args) {

        ArrayList<Integer> pentagonals = new ArrayList<Integer>();

        int i = 1;


        while (pentagonals.size() < 10_000) {
            pentagonals.add(i * (3 * i - 1) / 2);
            i++;
        }

        int smallestD = 1_000_000_000;

        for (int j = 0; j < pentagonals.size() - 1; j++) {
            for (int k = j + 1; k < pentagonals.size() - 1; k++) {
                int p1 = pentagonals.get(j);
                int p2 = pentagonals.get(k);

                if (isPentagonal(p1 + p2) && isPentagonal(p2 - p1)) {
                    if (p2 - p1 < smallestD) {
                        smallestD = p2 - p1;
                    }
                }

            }
        }

        System.out.println(smallestD);

    }

    public static boolean isPentagonal(int n) {
        double test = (Math.sqrt(24 * n + 1) + 1) / 6;

        return (int)test == test;
    }
}
